// Generated by the recordingTargets() plugin in vite.config.ts from
// L2-KPNS/metadata/recording_targets/{domain}_200.csv.
declare module "virtual:recording-targets" {
  /** Raw CSV text per entity domain; a domain without a CSV is missing. */
  export const csvByDomain: Partial<Record<string, string>>;
  /** The recording_targets directory that was read, or "" when none was found. */
  export const sourceDir: string;
}
